# Generated by Django 6.0.3 on 2026-03-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_user_userdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Postal_Code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
