# Generated by Django 6.0.3 on 2026-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spects',
            field=models.CharField(default=2, max_length=2000),
            preserve_default=False,
        ),
    ]
