# Generated by Django 6.0.3 on 2026-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_spects'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
