# Generated by Django 6.0.3 on 2026-04-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_body_product_bridge_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spects',
        ),
    ]
