# Generated by Django 6.0.3 on 2026-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_spects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scale',
            field=models.CharField(max_length=200),
        ),
    ]
